site_name: Meio a Meio
repo_url: https://github.com/mdsreq-fga-unb/2022.1-Meio-a-Meio
site_url: https://mdsreq-fga-unb.github.io/2022.1-Meio-a-Meio/
nav:
- Início: index.md
# - Projeto: ProductVision.md
- Produto:
  - 'Visão': ./produto-projeto/ProductVision.md
- Sprints planing:
  - 'Sprint 01': Sprints/Sprint01/SprintPlanning.md
  - 'Sprint 02': Sprints/Sprint02/SprintPlanning.md
  - 'Sprint 03': Sprints/Sprint03/SprintPlanning.md
  - 'Sprint 04': Sprints/Sprint04/SprintPlanning.md
- Sprints Review:
  - 'Sprint 01': Sprints/Sprint01/SprintReview.md
  - 'Sprint 02': Sprints/Sprint02/SprintReview.md
  - 'Sprint 03': Sprints/Sprint03/SprintReview.md
  - 'Sprint 04': Sprints/Sprint04/SprintReview.md


theme: 
  name: mkdocs

markdown_extensions:
  # - pymdownx.tasklist
  # - pymdownx.emoji
  # - pymdownx.mark
  # - pymdownx.tilde
