site_name: Meio a Meio
repo_url: https://github.com/mdsreq-fga-unb/2022.1-Meio-a-Meio
nav:
- Início: index.md
# - Projeto: ProductVision.md
- Produto:
  - 'Visão': ProductVision.md
- Tecnologia: tecnologias.md

theme: 
  name: mkdocs

markdown_extensions:
  # - pymdownx.tasklist
  # - pymdownx.emoji
  # - pymdownx.mark
  # - pymdownx.tilde